import streamlit as st
import pandas as pd
import streamlit.components.v1 as components

st.set_page_config(page_title="SilverWatch Dashboard", page_icon="🛡️", layout="wide")

st.title("🛡️ SilverWatch: AI-Powered Eldercare Isolation & Risk Dashboard")
st.markdown("Databricks & Open Data Hackathon Track A1 Prototype")

# Display metrics
col1, col2, col3 = st.columns(3)
col1.metric("Total Planning Areas Analyzed", "45+")
col2.metric("Primary Vulnerability Metric", "Composite Isolation Index")
col3.metric("Recommended Target Zones", "Top 10 Priority Areas")

tab1, tab2 = st.tabs(["🗺️ Geospatial Risk Heatmap", "📊 Prioritized Outreach List"])

with tab1:
    st.subheader("Interactive Planning Area Risk Map")
    st.markdown("Hover or click markers to inspect specific town vulnerability metrics.")
    try:
        with open('silverwatch_heatmap.html', 'r') as f:
            html_data = f.read()
        components.html(html_data, height=500)
    except FileNotFoundError:
        st.warning("Please run `silverwatch_master_pipeline.py` first to generate the heatmap HTML file.")

with tab2:
    st.subheader("Top 10 Priority Planning Areas for Active Ageing Centre (AAC) Support")
    # Display the static chart generated by the pipeline
    st.image('silverwatch_top10_risk.png', caption="Top 10 Planning Areas Risk Breakdown")
